[2022-05-15 21:42:45,612] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: GCPetlDAG.push_data_to_gcp 2022-05-15T21:42:36.697378+00:00 [queued]>
[2022-05-15 21:42:45,624] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: GCPetlDAG.push_data_to_gcp 2022-05-15T21:42:36.697378+00:00 [queued]>
[2022-05-15 21:42:45,624] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-05-15 21:42:45,624] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2022-05-15 21:42:45,624] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-05-15 21:42:45,629] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): push_data_to_gcp> on 2022-05-15T21:42:36.697378+00:00
[2022-05-15 21:42:45,634] {standard_task_runner.py:52} INFO - Started process 50200 to run task
[2022-05-15 21:42:45,636] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'GCPetlDAG', 'push_data_to_gcp', '2022-05-15T21:42:36.697378+00:00', '--job-id', '8', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_gcpPipeLine.py', '--cfg-path', '/tmp/tmpg_td3jzw', '--error-file', '/tmp/tmpmfqs5t0k']
[2022-05-15 21:42:45,638] {standard_task_runner.py:77} INFO - Job 8: Subtask push_data_to_gcp
[2022-05-15 21:42:45,662] {logging_mixin.py:104} INFO - Running <TaskInstance: GCPetlDAG.push_data_to_gcp 2022-05-15T21:42:36.697378+00:00 [running]> on host 7190ca705fc5
[2022-05-15 21:42:45,708] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=msbeni
AIRFLOW_CTX_DAG_ID=GCPetlDAG
AIRFLOW_CTX_TASK_ID=push_data_to_gcp
AIRFLOW_CTX_EXECUTION_DATE=2022-05-15T21:42:36.697378+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-15T21:42:36.697378+00:00
[2022-05-15 21:42:46,043] {logging_mixin.py:104} INFO - Encountered errors while inserting rows: [{'index': 0, 'errors': [{'reason': 'invalid', 'location': 'timestamp', 'debugInfo': '', 'message': 'Invalid datetime string "May 15, 2022 21:42:00 UTC"'}]}]
[2022-05-15 21:42:46,043] {python.py:151} INFO - Done. Returned value was: None
[2022-05-15 21:42:46,070] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=GCPetlDAG, task_id=push_data_to_gcp, execution_date=20220515T214236, start_date=20220515T214245, end_date=20220515T214246
[2022-05-15 21:42:46,107] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-05-15 21:42:46,131] {local_task_job.py:151} INFO - Task exited with return code 0
