[2022-05-14 02:49:58,599] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: pyDAGdec.store 2022-05-14T02:49:56.231148+00:00 [queued]>
[2022-05-14 02:49:58,611] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: pyDAGdec.store 2022-05-14T02:49:56.231148+00:00 [queued]>
[2022-05-14 02:49:58,611] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-05-14 02:49:58,611] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2022-05-14 02:49:58,612] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-05-14 02:49:58,616] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): store> on 2022-05-14T02:49:56.231148+00:00
[2022-05-14 02:49:58,621] {standard_task_runner.py:52} INFO - Started process 6427 to run task
[2022-05-14 02:49:58,623] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'pyDAGdec', 'store', '2022-05-14T02:49:56.231148+00:00', '--job-id', '7', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_pydag_decorator.py', '--cfg-path', '/tmp/tmpuw6w_zg_', '--error-file', '/tmp/tmpnliq9t3a']
[2022-05-14 02:49:58,625] {standard_task_runner.py:77} INFO - Job 7: Subtask store
[2022-05-14 02:49:58,664] {logging_mixin.py:104} INFO - Running <TaskInstance: pyDAGdec.store 2022-05-14T02:49:56.231148+00:00 [running]> on host d011519e5366
[2022-05-14 02:49:58,706] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=pyDAGdec
AIRFLOW_CTX_TASK_ID=store
AIRFLOW_CTX_EXECUTION_DATE=2022-05-14T02:49:56.231148+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-14T02:49:56.231148+00:00
[2022-05-14 02:49:58,706] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2022-05-14 02:49:58,706] {subprocess.py:63} INFO - Running command: ['bash', '-c', "echo 'store is called'"]
[2022-05-14 02:49:58,712] {subprocess.py:75} INFO - Output:
[2022-05-14 02:49:58,714] {subprocess.py:79} INFO - store is called
[2022-05-14 02:49:58,714] {subprocess.py:83} INFO - Command exited with return code 0
[2022-05-14 02:49:58,736] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=pyDAGdec, task_id=store, execution_date=20220514T024956, start_date=20220514T024958, end_date=20220514T024958
[2022-05-14 02:49:58,760] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-05-14 02:49:58,795] {local_task_job.py:151} INFO - Task exited with return code 0
