[2022-05-12 21:41:13,985] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: my_dag.my_task_1 2022-05-12T21:38:02.795437+00:00 [queued]>
[2022-05-12 21:41:13,996] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: my_dag.my_task_1 2022-05-12T21:38:02.795437+00:00 [queued]>
[2022-05-12 21:41:13,996] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-05-12 21:41:13,996] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2022-05-12 21:41:13,997] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-05-12 21:41:14,005] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): my_task_1> on 2022-05-12T21:38:02.795437+00:00
[2022-05-12 21:41:14,010] {standard_task_runner.py:52} INFO - Started process 1404 to run task
[2022-05-12 21:41:14,012] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'my_dag', 'my_task_1', '2022-05-12T21:38:02.795437+00:00', '--job-id', '14', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpu8anfglc', '--error-file', '/tmp/tmpadmuwgfb']
[2022-05-12 21:41:14,014] {standard_task_runner.py:77} INFO - Job 14: Subtask my_task_1
[2022-05-12 21:41:14,040] {logging_mixin.py:104} INFO - Running <TaskInstance: my_dag.my_task_1 2022-05-12T21:38:02.795437+00:00 [running]> on host 7b5fcf14949b
[2022-05-12 21:41:14,076] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=msbeni
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=my_task_1
AIRFLOW_CTX_EXECUTION_DATE=2022-05-12T21:38:02.795437+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-12T21:38:02.795437+00:00
[2022-05-12 21:41:14,077] {logging_mixin.py:104} INFO - 2022-05-12
[2022-05-12 21:41:14,077] {python.py:151} INFO - Done. Returned value was: None
[2022-05-12 21:41:14,083] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=my_task_1, execution_date=20220512T213802, start_date=20220512T214113, end_date=20220512T214114
[2022-05-12 21:41:14,098] {dagrun.py:496} WARNING - Failed to get task '<TaskInstance: my_dag.my_task 2022-05-12 21:38:02.795437+00:00 [removed]>' for dag 'my_dag'. Marking it as removed.
[2022-05-12 21:41:14,101] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-05-12 21:41:14,144] {local_task_job.py:151} INFO - Task exited with return code 0
