[2022-05-14 01:19:30,979] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: pyDAG.task_1 2022-05-13T00:00:00+00:00 [queued]>
[2022-05-14 01:19:30,991] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: pyDAG.task_1 2022-05-13T00:00:00+00:00 [queued]>
[2022-05-14 01:19:30,991] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-05-14 01:19:30,991] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2022-05-14 01:19:30,992] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-05-14 01:19:30,997] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): task_1> on 2022-05-13T00:00:00+00:00
[2022-05-14 01:19:31,002] {standard_task_runner.py:52} INFO - Started process 1390 to run task
[2022-05-14 01:19:31,004] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'pyDAG', 'task_1', '2022-05-13T00:00:00+00:00', '--job-id', '2', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_pydag.py', '--cfg-path', '/tmp/tmpe1eaw7q4', '--error-file', '/tmp/tmpenb4nz_r']
[2022-05-14 01:19:31,005] {standard_task_runner.py:77} INFO - Job 2: Subtask task_1
[2022-05-14 01:19:31,032] {logging_mixin.py:104} INFO - Running <TaskInstance: pyDAG.task_1 2022-05-13T00:00:00+00:00 [running]> on host d011519e5366
[2022-05-14 01:19:31,071] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=mohasa
AIRFLOW_CTX_DAG_ID=pyDAG
AIRFLOW_CTX_TASK_ID=task_1
AIRFLOW_CTX_EXECUTION_DATE=2022-05-13T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-13T00:00:00+00:00
[2022-05-14 01:19:31,071] {logging_mixin.py:104} INFO - Hello task_a
[2022-05-14 01:19:31,071] {python.py:151} INFO - Done. Returned value was: None
[2022-05-14 01:19:31,077] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=pyDAG, task_id=task_1, execution_date=20220513T000000, start_date=20220514T011930, end_date=20220514T011931
[2022-05-14 01:19:31,092] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-05-14 01:19:31,135] {local_task_job.py:151} INFO - Task exited with return code 0
